### ISSUE TITLE
present enduser with a file progresspage

### ISSUE THREAD

**Issue by piwi3910** [intagger/paraproxio#1]
as the download is handles by the proxy the webbrowser will not see any download and will hang in Loading until the file is fully downloaded.
This will confuse users.

Solution would be -> On download of an accelerated file -> popup and NEW window. with a simple progress bar of the file download
Once download is done -> present a button that once clicked downloads the full reconstructed file from the proxy.

Extra button needed: 1 Cancel button to cancel the download before finished.

**Comment by intagger** [comment]
Added partial response sending in 0cfdac786f21dae9c0efba7e311c6e4fff677c0f.
Now a client receives partial (with a fixed part size) responses and can see the actual progress of downloading of a big file on the proxy. No need for any popup window, etc.
